import { db } from "@/lib/db";
import type {
  BillingModel,
  Client,
  ClientSnapshot,
  EntityProfile,
  Invoice,
  InvoiceLineItem,
  InvoiceStatus,
  PlaceOfSupply,
  Remittance,
  StoredInvoiceStatus,
  TaxTreatment,
} from "@/lib/types";
import { newId, nowIso } from "@/lib/ids";
import { financialYearOf, todayIsoDate } from "@/lib/fy";
import { allocateSequence, formatSerialNumber } from "@/lib/serial";
import { invoiceTotalFcy, round2 } from "@/lib/money";
import { postInvoiceIssued, reverseSource } from "@/lib/ledger";
import { recordAudit } from "@/lib/audit";
import { enqueueSync } from "@/lib/sync";

export function snapshotOf(client: Client): ClientSnapshot {
  return {
    name: client.name,
    country: client.country,
    billingAddress: client.billingAddress,
    deliveryAddress: client.deliveryAddress,
    taxId: client.taxId,
    primaryContact: client.primaryContact,
    defaultCurrency: client.defaultCurrency,
    placeOfSupply: client.placeOfSupply,
    gstin: client.gstin,
    state: client.state,
  };
}

/**
 * The GST rate offered on a domestic invoice. 18% is the common rate for
 * consultancy, so it saves typing — the app is not determining that it applies,
 * and it stays editable on every invoice (CLAUDE.md, Tax scope boundary).
 */
export const DEFAULT_DOMESTIC_GST_RATE = 18;

export interface InvoiceTaxFace {
  placeOfSupply: PlaceOfSupply;
  taxTreatment: TaxTreatment;
  gstRate: number;
  sacCode?: string;
  igstDisclaimerShown: boolean;
}

/**
 * Resolves the tax face of an invoice from the client's classification, with
 * anything the user stated explicitly winning.
 *
 * Export is the one case with no discretion in it: zero-rated under LUT means
 * the rate is 0 and the disclaimer is mandatory, so those are forced rather than
 * defaulted — an export invoice cannot be talked into carrying tax. On a
 * domestic supply every figure is the user's.
 */
export function taxFaceOf(client: Client, override: Partial<InvoiceTaxFace> = {}): InvoiceTaxFace {
  const placeOfSupply = override.placeOfSupply ?? client.placeOfSupply;
  const sacCode = override.sacCode ?? client.defaultSacCode;

  if (placeOfSupply === "export") {
    return { placeOfSupply, taxTreatment: "zero_rated_export", gstRate: 0, sacCode, igstDisclaimerShown: true };
  }

  return {
    placeOfSupply,
    taxTreatment: override.taxTreatment ?? client.defaultTaxTreatment ?? "igst",
    gstRate: override.gstRate ?? client.defaultGstRate ?? DEFAULT_DOMESTIC_GST_RATE,
    sacCode,
    igstDisclaimerShown: false,
  };
}

/** Total FCY already received against an invoice. */
export function receivedFcy(remittances: Remittance[]): number {
  return round2(remittances.reduce((sum, r) => sum + r.fcyReceived, 0));
}

export function outstandingFcy(invoice: Invoice, remittances: Remittance[]): number {
  return round2(invoiceTotalFcy(invoice) - receivedFcy(remittances));
}

/**
 * An invoice counts as covered once remittances reach its total. The small
 * tolerance absorbs the rounding a bank applies to the FCY it credits; without
 * it a payment short by 0.001 would leave the invoice open forever.
 */
export function isFullyCovered(invoice: Invoice, remittances: Remittance[]): boolean {
  return outstandingFcy(invoice, remittances) <= 0.01;
}

/**
 * Display status (module 1, US-3). "Overdue" is a function of the due date and
 * what is still outstanding, so it is computed here on every read rather than
 * stored — a stored flag would be wrong the day after it was written.
 */
export function deriveInvoiceStatus(
  invoice: Invoice,
  remittances: Remittance[] = [],
  today = todayIsoDate()
): InvoiceStatus {
  if (invoice.status === "paid") return "paid";
  if (invoice.status === "draft") return "draft";
  if (isFullyCovered(invoice, remittances)) return "paid";
  return invoice.dueDate < today ? "overdue" : "sent";
}

export interface InvoiceDraftInput {
  clientId: string;
  currency: string;
  lineItems: InvoiceLineItem[];
  invoiceDate: string;
  dueDate: string;
  invoiceDateFxRate: number;
  notes?: string;
  status: StoredInvoiceStatus;

  /** Omit to take the client's classification and defaults — see `taxFaceOf`. */
  placeOfSupply?: PlaceOfSupply;
  taxTreatment?: TaxTreatment;
  gstRate?: number;
  sacCode?: string;
  /** The client's purchase order reference, for a payables desk that matches on one. */
  poNumber?: string;
  /** Rule 46(p) — whether the recipient pays the tax under reverse charge. */
  reverseCharge?: boolean;

  billingModel?: BillingModel;
  /** The retainer period being billed, when this invoice covers one. */
  periodStart?: string;
  periodEnd?: string;
  autoGenerated?: boolean;
}

/**
 * Creates an invoice and, if it is being issued straight away rather than saved
 * as a draft, posts it to the ledger. The serial number is consumed from the
 * financial-year counter so two concurrent saves can never share one.
 */
export async function createInvoice(
  input: InvoiceDraftInput,
  profile: Pick<EntityProfile, "invoiceSerialPrefix" | "invoiceSerialPadding">
): Promise<Invoice> {
  const client = await db.clients.get(input.clientId);
  if (!client) throw new Error("Select a client before saving this invoice.");

  const financialYear = financialYearOf(input.invoiceDate);
  const sequence = await allocateSequence(financialYear);
  const timestamp = nowIso();

  const invoice: Invoice = {
    id: newId(),
    serialNumber: formatSerialNumber(profile, financialYear, sequence),
    financialYear,
    sequence,
    clientId: client.id,
    clientSnapshot: snapshotOf(client),
    currency: input.currency,
    lineItems: input.lineItems,
    invoiceDate: input.invoiceDate,
    dueDate: input.dueDate,
    invoiceDateFxRate: input.invoiceDateFxRate,
    status: input.status,
    manualStatusOverride: false,
    notes: input.notes,
    poNumber: input.poNumber,
    reverseCharge: input.reverseCharge ?? false,
    ...taxFaceOf(client, input),
    billingModel: input.billingModel ?? client.billing.model,
    periodStart: input.periodStart,
    periodEnd: input.periodEnd,
    autoGenerated: input.autoGenerated,
    createdAt: timestamp,
    updatedAt: timestamp,
  };

  await db.transaction("rw", db.invoices, db.ledgerEntries, db.auditLog, db.syncQueue, async (tx) => {
    await db.invoices.add(invoice);
    await enqueueSync(tx, "invoices", invoice.id);
    if (invoice.status !== "draft") await postInvoiceIssued(invoice, tx);
    await recordAudit(
      {
        actionType: "invoice_created",
        entityType: "invoice",
        entityId: invoice.id,
        summary: `${invoice.serialNumber} for ${invoice.clientSnapshot.name} — ${invoice.currency} ${invoiceTotalFcy(invoice)}`,
        after: invoice,
      },
      tx
    );
  });

  return invoice;
}

/** True if a patch carries anything that decides how tax prints on the invoice. */
function touchesTaxFace(patch: Partial<InvoiceDraftInput>): boolean {
  return (
    patch.placeOfSupply !== undefined ||
    patch.taxTreatment !== undefined ||
    patch.gstRate !== undefined ||
    patch.sacCode !== undefined
  );
}

/**
 * Edits an existing invoice. Issued invoices have already hit the ledger, so a
 * change to their amounts is applied as a reversal plus a fresh posting rather
 * than by rewriting history. The serial number is never reissued.
 */
export async function updateInvoice(id: string, patch: Partial<InvoiceDraftInput>): Promise<void> {
  await db.transaction("rw", db.invoices, db.clients, db.ledgerEntries, db.auditLog, db.syncQueue, async (tx) => {
    const before = await db.invoices.get(id);
    if (!before) throw new Error("Invoice no longer exists.");

    const after: Invoice = { ...before, ...patch, updatedAt: nowIso() };

    if (patch.clientId && patch.clientId !== before.clientId) {
      const client = await db.clients.get(patch.clientId);
      if (!client) throw new Error("Select a client before saving this invoice.");
      after.clientSnapshot = snapshotOf(client);
      // Moving an invoice to a differently classified client has to move its tax
      // face too — otherwise a domestic invoice keeps printing the LUT export
      // disclaimer, which would be a false statement about the supply.
      Object.assign(after, taxFaceOf(client, patch));
    } else if (touchesTaxFace(patch)) {
      // The spread above would have taken a stray rate at face value. Routing it
      // back through `taxFaceOf` keeps the one rule that has no discretion in it:
      // an export invoice is zero-rated and carries the disclaimer, whatever the
      // caller sent.
      const client = await db.clients.get(before.clientId);
      if (client) Object.assign(after, taxFaceOf(client, { ...patch, placeOfSupply: before.placeOfSupply }));
    }

    await db.invoices.put(after);
    await enqueueSync(tx, "invoices", id);

    if (before.status !== "draft") await reverseSource("invoice", id, after.invoiceDate, tx);
    if (after.status !== "draft") await postInvoiceIssued(after, tx);

    await recordAudit(
      {
        actionType: "invoice_updated",
        entityType: "invoice",
        entityId: id,
        summary: `${after.serialNumber} updated`,
        before,
        after,
      },
      tx
    );
  });
}

/**
 * Changes the stored status. `isManualOverride` should be true when the user is
 * forcing a state the data does not support — marking Paid with no covering
 * remittance — so the audit trail flags it distinctly (module 8, US-2).
 */
export async function setInvoiceStatus(
  id: string,
  next: StoredInvoiceStatus,
  options: { isManualOverride?: boolean } = {}
): Promise<void> {
  await db.transaction("rw", db.invoices, db.ledgerEntries, db.auditLog, db.syncQueue, async (tx) => {
    const before = await db.invoices.get(id);
    if (!before) throw new Error("Invoice no longer exists.");
    if (before.status === next) return;

    const isManualOverride = options.isManualOverride ?? false;
    const after: Invoice = {
      ...before,
      status: next,
      manualStatusOverride: isManualOverride || before.manualStatusOverride,
      updatedAt: nowIso(),
    };
    await db.invoices.put(after);
    await enqueueSync(tx, "invoices", id);

    // Leaving Draft is what turns the invoice into a receivable; returning to
    // Draft unwinds that. Sent <-> Paid has no ledger effect on its own — cash
    // is recognised by the remittance, not by the status flag.
    if (before.status === "draft" && next !== "draft") await postInvoiceIssued(after, tx);
    if (before.status !== "draft" && next === "draft") {
      await reverseSource("invoice", id, after.invoiceDate, tx);
    }

    const overrideNote = isManualOverride ? " (manual override)" : "";
    await recordAudit(
      {
        actionType: isManualOverride ? "invoice_status_overridden" : "invoice_status_changed",
        entityType: "invoice",
        entityId: id,
        summary: `${after.serialNumber}: ${before.status} to ${next}${overrideNote}`,
        isManualOverride,
        before: { status: before.status },
        after: { status: next },
      },
      tx
    );
  });
}

/**
 * Deletes an invoice. The financial-year counter is deliberately NOT rolled
 * back — the serial is spent for good, leaving a documented gap in the series
 * rather than a number that could be reissued to a different client.
 */
export async function deleteInvoice(id: string): Promise<void> {
  await db.transaction(
    "rw",
    db.invoices,
    db.remittances,
    db.ledgerEntries,
    db.auditLog,
    db.syncQueue,
    async (tx) => {
      const invoice = await db.invoices.get(id);
      if (!invoice) return;

      const remittanceCount = await db.remittances.where("invoiceId").equals(id).count();
      if (remittanceCount > 0) {
        throw new Error(
          "This invoice has remittances recorded against it. Delete those first if it really is a mistake."
        );
      }

      if (invoice.status !== "draft") await reverseSource("invoice", id, invoice.invoiceDate, tx);
      await db.invoices.delete(id);
      await enqueueSync(tx, "invoices", id);

      await recordAudit(
        {
          actionType: "invoice_deleted",
          entityType: "invoice",
          entityId: id,
          summary: `${invoice.serialNumber} deleted — serial not reused`,
          isManualOverride: true,
          before: invoice,
        },
        tx
      );
    }
  );
}
