import {
  test,
  expect,
  readTable,
  addClient,
  addInvoice,
  completeEntityProfile,
  openPrimaryAction,
  openInvoice,
  expectLedgerBalanced,
  accountBalance,
  type LedgerEntryShape,
  type AuditEntryShape,
} from "./fixtures";

/**
 * Phase 2 — how an engagement is agreed, and what that makes an invoice say.
 *
 * Four things arrived together and are covered here because they only make sense
 * together: the signed paper attached to a client, the billing style it sets, the
 * place-of-supply classification, and the date-wise consultation lines an hourly
 * engagement produces.
 *
 * Two rules are asserted against the store rather than the screen, because
 * getting them wrong is a filing problem rather than a display one:
 *   - an export invoice stays zero-rated and keeps the LUT declaration, whatever
 *     GST defaults a client carries;
 *   - a retainer period is drafted once and never again — every auto-draft
 *     permanently consumes an invoice serial.
 */

interface ClientShape {
  id: string;
  name: string;
  country: string;
  placeOfSupply: string;
  defaultCurrency: string;
  gstin?: string;
  state?: string;
  defaultGstRate?: number;
  defaultTaxTreatment?: string;
  defaultSacCode?: string;
  billing: {
    model: string;
    hourlyRate?: number;
    fixedAmount?: number;
    cycle?: { intervalUnit: string; intervalCount: number };
    cycleAnchorDate?: string;
    autoDraft: boolean;
    lastDraftedPeriodStart?: string;
  };
}

interface TaxedInvoiceShape {
  id: string;
  serialNumber: string;
  status: string;
  currency: string;
  placeOfSupply: string;
  taxTreatment: string;
  gstRate: number;
  sacCode?: string;
  igstDisclaimerShown: boolean;
  billingModel: string;
  autoGenerated?: boolean;
  periodStart?: string;
  periodEnd?: string;
  lineItems: { description: string; quantity: number; unitPrice: number; unit: string; date?: string }[];
}

interface DocumentShape {
  id: string;
  clientId: string;
  kind: string;
  fileName: string;
  size: number;
  analysis?: {
    parties: string[];
    effectiveDate?: string;
    paymentTermsDays?: number;
    confidentialityYears?: number;
    governingLaw?: string;
    rates: { amount: number; currency?: string; unit?: string }[];
    warnings: string[];
  };
}

interface Engagement {
  name: string;
  placeOfSupply?: "export" | "domestic";
  country?: string;
  currency?: string;
  gstin?: string;
  state?: string;
  taxTreatment?: "IGST" | "CGST + SGST";
  gstRate?: string;
  sacCode?: string;
  billingModel?: "hourly" | "fixed";
  hourlyRate?: string;
  fixedAmount?: string;
  frequency?: string;
  intervalCount?: string;
  intervalUnit?: "Weeks" | "Months";
  anchorDate?: string;
  autoDraft?: boolean;
}

/**
 * Onboards a client through the sheet, across both of its tabs.
 *
 * Deliberately UI-driven: the classification and the billing style are decided
 * by form logic — the currency list narrows on a place-of-supply change, the
 * frequency fields appear only for a fixed payout — and seeding the table
 * directly would test none of it.
 */
async function onboard(page: import("@playwright/test").Page, client: Engagement): Promise<void> {
  await page.goto("/clients");
  await openPrimaryAction(page, "New client");
  const sheet = page.getByRole("dialog");

  await sheet.getByLabel("Client name").fill(client.name);

  if (client.placeOfSupply === "domestic") {
    await sheet.getByLabel("Place of supply").click();
    await page.getByRole("option", { name: /Domestic supply/ }).click();
  }

  await sheet.getByLabel("Country").fill(client.country ?? "United States");

  if (client.currency) {
    await sheet.getByLabel("Default currency").click();
    await page.getByRole("option", { name: new RegExp(`^${client.currency}\\b`) }).click();
  }
  if (client.gstin) await sheet.getByLabel("Client GSTIN").fill(client.gstin);
  if (client.state) await sheet.getByLabel("State").fill(client.state);
  if (client.taxTreatment) {
    await sheet.getByLabel("Tax treatment").click();
    await page.getByRole("option", { name: client.taxTreatment, exact: true }).click();
  }
  if (client.gstRate) await sheet.getByLabel("GST rate (%)").fill(client.gstRate);
  if (client.sacCode) await sheet.getByLabel("SAC code").fill(client.sacCode);

  await sheet.getByRole("tab", { name: "Billing" }).click();

  if (client.billingModel === "fixed") {
    await sheet.getByLabel("Billing style").click();
    await page.getByRole("option", { name: /Fixed payout/ }).click();
  }
  if (client.hourlyRate) await sheet.getByLabel("Rate per hour").fill(client.hourlyRate);
  if (client.fixedAmount) await sheet.getByLabel("Amount per period").fill(client.fixedAmount);
  if (client.frequency) {
    await sheet.getByLabel("Frequency").click();
    await page.getByRole("option", { name: client.frequency }).click();
  }
  if (client.intervalCount) await sheet.getByLabel("Every").fill(client.intervalCount);
  if (client.intervalUnit) {
    await sheet.getByLabel("Unit").click();
    await page.getByRole("option", { name: client.intervalUnit, exact: true }).click();
  }
  if (client.anchorDate) await sheet.getByLabel("First period starts").fill(client.anchorDate);
  if (client.autoDraft) await sheet.getByRole("switch").click();

  await sheet.getByRole("button", { name: "Add client" }).click();
  await expect(page.getByText(`${client.name} added.`)).toBeVisible();
}

/** The first day of the month `offset` months from this one, as an ISO date. */
function monthStart(offset: number): string {
  const now = new Date();
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + offset, 1))
    .toISOString()
    .slice(0, 10);
}

const CONSULTING_AGREEMENT = [
  "CONSULTING AGREEMENT",
  "",
  "This Agreement is entered into between Rahul Goel HUF and Northwind Labs Inc, effective from 1 April 2027.",
  "",
  "3. FEES. The Consultant's fee shall be USD 150 per hour for all services rendered under this Agreement.",
  "",
  "4. PAYMENT. Invoices are payable within thirty (30) days of the date of the invoice.",
  "",
  "5. CONFIDENTIALITY. The obligations of confidentiality shall remain in effect for two (2) years.",
  "",
  "6. NOTICE. Either party may terminate this Agreement upon thirty (30) days written notice.",
  "",
  "7. GOVERNING LAW. This Agreement is governed by the laws of the Republic of India.",
].join("\n");

test.describe("engagement terms on a client", () => {
  test("records a domestic supply with the GST rate the user states", async ({ page }) => {
    await onboard(page, {
      name: "Bharat Systems Pvt Ltd",
      placeOfSupply: "domestic",
      country: "India",
      currency: "INR",
      gstin: "29ABCDE1234F1Z5",
      state: "Karnataka",
      taxTreatment: "CGST + SGST",
      gstRate: "18",
      sacCode: "998313",
    });

    const clients = await readTable<ClientShape>(page, "clients");
    expect(clients).toHaveLength(1);
    expect(clients[0]).toMatchObject({
      placeOfSupply: "domestic",
      defaultCurrency: "INR",
      gstin: "29ABCDE1234F1Z5",
      state: "Karnataka",
      defaultTaxTreatment: "cgst_sgst",
      defaultGstRate: 18,
      defaultSacCode: "998313",
    });

    await expect(page.getByText("Domestic supply", { exact: true })).toBeVisible();
  });

  test("offers the base currency only on a domestic supply", async ({ page }) => {
    await page.goto("/clients");
    await openPrimaryAction(page, "New client");
    const sheet = page.getByRole("dialog");

    // An export invoice billed in INR would have no foreign currency to realize
    // a gain against, which is the whole point of the forex module.
    await sheet.getByLabel("Default currency").click();
    await expect(page.getByRole("option", { name: /^USD\b/ })).toBeVisible();
    await expect(page.getByRole("option", { name: /^INR\b/ })).toBeHidden();
    await page.keyboard.press("Escape");

    await sheet.getByLabel("Place of supply").click();
    await page.getByRole("option", { name: /Domestic supply/ }).click();

    await sheet.getByLabel("Default currency").click();
    await expect(page.getByRole("option", { name: /^INR\b/ })).toBeVisible();
  });

  test("clears the domestic fields when a client is reclassified as an export", async ({ page }) => {
    await onboard(page, {
      name: "Bharat Systems Pvt Ltd",
      placeOfSupply: "domestic",
      country: "India",
      currency: "INR",
      gstin: "29ABCDE1234F1Z5",
      state: "Karnataka",
      gstRate: "18",
    });

    await page.goto("/clients");
    await page.getByRole("button", { name: "Edit" }).first().click();
    const sheet = page.getByRole("dialog");
    await sheet.getByLabel("Place of supply").click();
    await page.getByRole("option", { name: /Export of services/ }).click();
    await sheet.getByLabel("Country").fill("United States");
    await sheet.getByLabel("Default currency").click();
    await page.getByRole("option", { name: /^USD\b/ }).click();
    await sheet.getByRole("button", { name: "Save changes" }).click();
    await expect(page.getByText("Bharat Systems Pvt Ltd updated.")).toBeVisible();

    // A stale GSTIN left on the row would print on an export invoice.
    const clients = await readTable<ClientShape>(page, "clients");
    expect(clients[0].placeOfSupply).toBe("export");
    expect(clients[0].gstin).toBeUndefined();
    expect(clients[0].state).toBeUndefined();
    expect(clients[0].defaultGstRate).toBeUndefined();
  });

  test("stores an hourly rate", async ({ page }) => {
    await onboard(page, { name: "Northwind Labs", currency: "USD", hourlyRate: "150" });

    const clients = await readTable<ClientShape>(page, "clients");
    expect(clients[0].billing).toMatchObject({ model: "hourly", hourlyRate: 150 });
    await expect(page.getByText("$150.00 / hour")).toBeVisible();
  });

  test("stores a fixed payout on a custom frequency", async ({ page }) => {
    await onboard(page, {
      name: "Globex Retainer",
      currency: "EUR",
      billingModel: "fixed",
      fixedAmount: "5000",
      frequency: "Custom…",
      intervalCount: "2",
      intervalUnit: "Weeks",
      anchorDate: "2027-04-01",
    });

    const clients = await readTable<ClientShape>(page, "clients");
    expect(clients[0].billing).toMatchObject({
      model: "fixed",
      fixedAmount: 5000,
      cycle: { intervalUnit: "week", intervalCount: 2 },
      cycleAnchorDate: "2027-04-01",
      autoDraft: false,
    });
    await expect(page.getByText("Every 2 weeks")).toBeVisible();
  });

  test("refuses to auto-draft without a date to count periods from", async ({ page }) => {
    await page.goto("/clients");
    await openPrimaryAction(page, "New client");
    const sheet = page.getByRole("dialog");

    await sheet.getByLabel("Client name").fill("No Anchor Ltd");
    await sheet.getByLabel("Country").fill("Singapore");
    await sheet.getByRole("tab", { name: "Billing" }).click();
    await sheet.getByLabel("Billing style").click();
    await page.getByRole("option", { name: /Fixed payout/ }).click();
    await sheet.getByRole("switch").click();
    await sheet.getByRole("button", { name: "Add client" }).click();

    await expect(
      sheet.getByText("Required to draft automatically — periods are counted from this date.")
    ).toBeVisible();
    expect(await readTable(page, "clients")).toHaveLength(0);
  });
});

test.describe("contract analysis", () => {
  test("reads terms out of an attached agreement and copies them into billing", async ({ page }) => {
    await page.goto("/clients");
    await openPrimaryAction(page, "New client");
    const sheet = page.getByRole("dialog");

    await sheet.getByLabel("Client name").fill("Northwind Labs Inc");
    await sheet.getByLabel("Country").fill("United States");
    await sheet.getByRole("tab", { name: /Documents/ }).click();

    await page.getByLabel("Contract or NDA").setInputFiles({
      name: "northwind-nda.txt",
      mimeType: "text/plain",
      buffer: Buffer.from(CONSULTING_AGREEMENT, "utf-8"),
    });

    await expect(sheet.getByText("Terms found in the document")).toBeVisible();
    await expect(sheet.getByText("2027-04-01")).toBeVisible();
    await expect(sheet.getByText("30 days").first()).toBeVisible();
    await expect(sheet.getByText("2 years")).toBeVisible();
    await expect(sheet.getByText("USD 150 per hour")).toBeVisible();

    // The engine proposes; nothing reaches the record until it is accepted.
    await sheet.getByRole("button", { name: "Use these terms" }).click();
    await expect(page.getByText("Filled in from the contract")).toBeVisible();
    await expect(sheet.getByLabel("Rate per hour")).toHaveValue("150");

    await sheet.getByRole("button", { name: "Add client" }).click();
    await expect(page.getByText("Northwind Labs Inc added.")).toBeVisible();

    const documents = await readTable<DocumentShape>(page, "clientDocuments");
    expect(documents).toHaveLength(1);
    expect(documents[0]).toMatchObject({ kind: "nda", fileName: "northwind-nda.txt" });
    expect(documents[0].analysis!.paymentTermsDays).toBe(30);
    expect(documents[0].analysis!.governingLaw).toContain("Republic of India");
    expect(documents[0].analysis!.rates[0]).toMatchObject({
      amount: 150,
      currency: "USD",
      unit: "hour",
    });

    const clients = await readTable<ClientShape>(page, "clients");
    expect(clients[0].billing).toMatchObject({ model: "hourly", hourlyRate: 150 });

    const audit = await readTable<AuditEntryShape>(page, "auditLog");
    expect(audit.map((entry) => entry.actionType)).toContain("client_document_uploaded");
  });

  test("keeps a file it could not read, and says so", async ({ page }) => {
    await page.goto("/clients");
    await openPrimaryAction(page, "New client");
    const sheet = page.getByRole("dialog");

    await sheet.getByLabel("Client name").fill("Scanned Paper Ltd");
    await sheet.getByLabel("Country").fill("United Arab Emirates");
    await sheet.getByRole("tab", { name: /Documents/ }).click();

    await page.getByLabel("Contract or NDA").setInputFiles({
      name: "scan.txt",
      mimeType: "text/plain",
      buffer: Buffer.from("", "utf-8"),
    });

    // Unreadable is not a reason to refuse the file: the signed document still
    // has to live somewhere, and the terms can be typed in.
    await expect(sheet.getByText(/No text could be read from this file/)).toBeVisible();
    await expect(sheet.getByRole("button", { name: "Use these terms" })).toBeHidden();

    await sheet.getByRole("button", { name: "Add client" }).click();
    await expect(page.getByText("Scanned Paper Ltd added.")).toBeVisible();

    const documents = await readTable<DocumentShape>(page, "clientDocuments");
    expect(documents).toHaveLength(1);
    expect(documents[0].analysis!.warnings.join(" ")).toContain("No readable text");
  });
});

test.describe("date-wise consultation billing", () => {
  test.beforeEach(async ({ page }) => {
    await completeEntityProfile(page);
    await onboard(page, { name: "Northwind Labs", currency: "USD", hourlyRate: "200" });
  });

  test("itemises consultations by date, with hours and a rate per hour", async ({ page }) => {
    await page.goto("/invoices");
    await openPrimaryAction(page, "New invoice");
    const sheet = page.getByRole("dialog");

    await sheet.getByLabel("Client").click();
    await page.getByRole("option", { name: /Northwind Labs/ }).click();

    // The client's billing style drives the editor — nothing to switch by hand.
    await expect(
      sheet.getByRole("combobox").filter({ hasText: /Itemised by date|Fixed amounts/ })
    ).toContainText("Itemised by date");
    await expect(sheet.getByLabel(/^Rate\/hour \(/)).toHaveValue("200");

    await sheet.getByLabel(/Exchange rate on invoice date/).fill("83");
    await sheet.getByLabel("Date").fill("2027-04-01");
    await sheet.getByLabel("Consultation").fill("Architecture review call");
    await sheet.getByLabel("Hours").fill("2.5");

    await sheet.getByRole("button", { name: "Add line" }).click();
    // The date carries forward from the previous line rather than resetting to
    // today: consultations are usually logged in a batch, days after the fact.
    await expect(sheet.getByLabel("Date").nth(1)).toHaveValue("2027-04-01");
    await sheet.getByLabel("Date").nth(1).fill("2027-04-03");
    await sheet.getByLabel("Consultation").nth(1).fill("Migration planning");
    await sheet.getByLabel("Hours").nth(1).fill("1.5");

    await expect(sheet.getByText("4.00 hrs", { exact: true })).toBeVisible();
    await expect(sheet.getByText("$800.00").first()).toBeVisible();

    await sheet.getByRole("button", { name: "Save & issue" }).click();
    await expect(page.getByText(/issued\.$/)).toBeVisible();

    const invoices = await readTable<TaxedInvoiceShape>(page, "invoices");
    expect(invoices[0].billingModel).toBe("hourly");
    expect(invoices[0].lineItems).toHaveLength(2);
    expect(invoices[0].lineItems[0]).toMatchObject({
      date: "2027-04-01",
      description: "Architecture review call",
      quantity: 2.5,
      unitPrice: 200,
      unit: "hours",
    });
    expect(invoices[0].lineItems[1]).toMatchObject({ date: "2027-04-03", quantity: 1.5 });

    await openInvoice(page, invoices[0].serialNumber);
    const detail = page.getByRole("dialog");
    await expect(detail.getByText("4.00 hrs over 2 dates")).toBeVisible();
    await expect(detail.getByText("2027-04-01")).toBeVisible();
    await expect(detail.getByText(/2\.5 hrs × \$200\.00 \/ hour/)).toBeVisible();
  });

  test("refuses an hourly line with no date on it", async ({ page }) => {
    await page.goto("/invoices");
    await openPrimaryAction(page, "New invoice");
    const sheet = page.getByRole("dialog");

    await sheet.getByLabel("Client").click();
    await page.getByRole("option", { name: /Northwind Labs/ }).click();
    await sheet.getByLabel(/Exchange rate on invoice date/).fill("83");
    await sheet.getByLabel("Date").fill("");
    await sheet.getByLabel("Consultation").fill("Undated block of hours");
    await sheet.getByLabel("Hours").fill("6");
    await sheet.getByRole("button", { name: "Save & issue" }).click();

    // An unlabelled block of hours is not a record of consultation.
    await expect(sheet.getByText("Required — hourly lines are itemised by date.")).toBeVisible();
    expect(await readTable(page, "invoices")).toHaveLength(0);
  });
});

test.describe("tax face of an invoice", () => {
  test("posts a domestic invoice to domestic income and GST payable", async ({ page }) => {
    await completeEntityProfile(page);
    await onboard(page, {
      name: "Bharat Systems Pvt Ltd",
      placeOfSupply: "domestic",
      country: "India",
      currency: "INR",
      gstin: "29ABCDE1234F1Z5",
      state: "Karnataka",
      gstRate: "18",
      sacCode: "998313",
      billingModel: "fixed",
      fixedAmount: "10000",
    });

    await page.goto("/invoices");
    await openPrimaryAction(page, "New invoice");
    const sheet = page.getByRole("dialog");

    await sheet.getByLabel("Client").click();
    await page.getByRole("option", { name: /Bharat Systems/ }).click();
    // Billed in the base currency, so the books need no conversion.
    await expect(sheet.getByLabel("Currency")).toContainText("INR");
    await expect(sheet.getByLabel("GST rate (%)")).toHaveValue("18");
    await expect(sheet.getByLabel("SAC code")).toHaveValue("998313");

    // A rupee invoice has no rate to capture, so the field is not asked for at
    // all; the 1 it stores is filled by the form.
    await expect(sheet.getByLabel(/Exchange rate on invoice date/)).toHaveCount(0);
    await sheet.getByLabel("Description").fill("Retainer — April 2027");
    await sheet.getByLabel("Qty").fill("1");
    await sheet.getByLabel(/^Rate \(/).fill("10000");

    await expect(sheet.getByText("IGST @ 18%")).toBeVisible();
    await expect(sheet.getByText("₹11,800.00").first()).toBeVisible();

    await sheet.getByRole("button", { name: "Save & issue" }).click();
    await expect(page.getByText(/issued\.$/)).toBeVisible();

    const invoices = await readTable<TaxedInvoiceShape>(page, "invoices");
    expect(invoices[0]).toMatchObject({
      placeOfSupply: "domestic",
      taxTreatment: "igst",
      gstRate: 18,
      sacCode: "998313",
      // The export declaration would be a false statement about this supply.
      igstDisclaimerShown: false,
    });

    const entries = await readTable<LedgerEntryShape>(page, "ledgerEntries");
    expectLedgerBalanced(entries);
    expect(accountBalance(entries, "accounts_receivable")).toBe(11800);
    // GST collected is a liability, never income.
    expect(accountBalance(entries, "domestic_income")).toBe(-10000);
    expect(accountBalance(entries, "gst_payable")).toBe(-1800);
    expect(accountBalance(entries, "foreign_income")).toBe(0);

    await openInvoice(page, invoices[0].serialNumber);
    await expect(
      page.getByRole("dialog").getByText(/the export declaration is not printed/)
    ).toBeVisible();
  });

  test("leaves an export invoice zero-rated and declared", async ({ page }) => {
    await completeEntityProfile(page);
    await addClient(page, { name: "Acme Inc", country: "United States", currency: "USD" });
    const serial = await addInvoice(page, {
      clientName: "Acme Inc",
      fxRate: "83.00",
      unitPrice: "1000",
    });

    const invoices = await readTable<TaxedInvoiceShape>(page, "invoices");
    const invoice = invoices.find((i) => i.serialNumber === serial)!;
    expect(invoice).toMatchObject({
      placeOfSupply: "export",
      taxTreatment: "zero_rated_export",
      gstRate: 0,
      igstDisclaimerShown: true,
    });

    const entries = await readTable<LedgerEntryShape>(page, "ledgerEntries");
    expectLedgerBalanced(entries);
    expect(accountBalance(entries, "foreign_income")).toBe(-83000);
    // An empty GST line is dropped rather than posted as a zero.
    expect(entries.some((e) => e.account === "gst_payable")).toBe(false);

    await openInvoice(page, serial);
    await expect(page.getByRole("dialog").getByText("DECLARATION ON PDF")).toBeVisible();
  });
});

test.describe("recurring retainer drafts", () => {
  test("drafts each elapsed period once and never the same period twice", async ({ page }) => {
    await completeEntityProfile(page);
    await onboard(page, {
      name: "Globex Retainer",
      currency: "EUR",
      billingModel: "fixed",
      fixedAmount: "5000",
      frequency: "Monthly",
      // Two whole months have closed since this anchor; the month in progress has
      // not, and unfinished retainer time is not billable.
      anchorDate: monthStart(-2),
      autoDraft: true,
    });

    // A full page load is what runs the generator — it is mounted once in the
    // root layout, not on a route.
    await page.goto("/invoices");
    await expect
      .poll(async () => (await readTable<TaxedInvoiceShape>(page, "invoices")).length)
      .toBe(2);

    const drafts = await readTable<TaxedInvoiceShape>(page, "invoices");
    for (const draft of drafts) {
      expect(draft.status).toBe("draft");
      expect(draft.autoGenerated).toBe(true);
      expect(draft.billingModel).toBe("fixed");
      expect(draft.lineItems[0].unitPrice).toBe(5000);
    }
    expect(new Set(drafts.map((d) => d.periodStart)).size).toBe(2);
    expect(drafts.map((d) => d.periodStart)).toContain(monthStart(-2));
    expect(drafts.map((d) => d.periodStart)).toContain(monthStart(-1));

    const clients = await readTable<ClientShape>(page, "clients");
    expect(clients[0].billing.lastDraftedPeriodStart).toBe(monthStart(-1));

    // Nothing posts until a person issues them: a draft is not a supply.
    expect(await readTable(page, "ledgerEntries")).toHaveLength(0);

    const audit = await readTable<AuditEntryShape>(page, "auditLog");
    expect(audit.filter((e) => e.actionType === "invoice_auto_drafted")).toHaveLength(2);

    // Opening the app again must not re-draft: every draft permanently consumes
    // an invoice serial, and a reissued period would be a duplicate bill.
    await page.goto("/");
    await page.goto("/invoices");
    await expect(page.getByText("Globex Retainer").first()).toBeVisible();
    expect(await readTable<TaxedInvoiceShape>(page, "invoices")).toHaveLength(2);
  });

  test("leaves a client alone when auto-drafting is off", async ({ page }) => {
    await completeEntityProfile(page);
    await onboard(page, {
      name: "Manual Retainer",
      currency: "EUR",
      billingModel: "fixed",
      fixedAmount: "5000",
      frequency: "Monthly",
      anchorDate: monthStart(-2),
    });

    await page.goto("/invoices");
    await expect(page.getByText(/No invoices/).first()).toBeVisible();
    expect(await readTable(page, "invoices")).toHaveLength(0);
  });
});
